export const GET_REQUEST: 'GET_REQUEST' = 'GET_REQUEST';
export const GET_REQUEST_SUCCESS: 'GET_REQUEST_SUCCESS' = 'GET_REQUEST_SUCCESS';
export const GET_REQUST_FAILED: 'GET_REQUST_FAILED' = 'GET_REQUST_FAILED';
export const CLOSE_DETAILS_MODAL: 'CLOSE_DETAILS_MODAL' = 'CLOSE_DETAILS_MODAL';
export const OPEN_DETAILS_MODAL: 'OPEN_DETAILS_MODAL' = 'OPEN_DETAILS_MODAL';
export const SELECT_RESULT: 'SELECT_RESULT' = 'SELECT_RESULT';
export const UNSELECT_RESULT: 'UNSELECT_RESULT' = 'UNSELECT_RESULT'
